# Server Port
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/factory1
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Disable Whitelabel Error Page
server.error.whitelabel.enabled=false

# Show SQL Errors in Console
spring.jpa.show-sql=true

# Static Pages Location
spring.web.resources.static-locations=classpath:/static/,classpath:/public/

# Enable Detailed Error Messages
server.error.include-message=always
server.error.include-binding-errors=always